// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241210131941_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.AkademikDanismanlarTbl", b =>
                {
                    b.Property<int>("DanismanlikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanismanlikID"));

                    b.Property<int>("EOYiliID")
                        .HasColumnType("int");

                    b.Property<int>("GorevID")
                        .HasColumnType("int");

                    b.Property<string>("KisimAdi")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("PerID")
                        .HasColumnType("int");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.HasKey("DanismanlikID");

                    b.ToTable("AkademikDanismanlarTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AppRolesTbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.AppUserTbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.AskeriSiniflarTbl", b =>
                {
                    b.Property<int>("SinifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinifID"));

                    b.Property<string>("SinifKisa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SinifUzun")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SinifID");

                    b.ToTable("AskeriSiniflarTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.BirimlerTbl", b =>
                {
                    b.Property<int>("BirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BirimID"));

                    b.Property<string>("BirimAdi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BirimID");

                    b.ToTable("BirimlerTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.BolumTbl", b =>
                {
                    b.Property<int>("BolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumID"));

                    b.Property<string>("BolumAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BolumID");

                    b.ToTable("BolumlerTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.DerslerTbl", b =>
                {
                    b.Property<string>("DersKodu")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("AKTS")
                        .HasColumnType("int");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("DersAdi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EOYiliID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HaftalikDS")
                        .HasColumnType("int");

                    b.Property<float>("Kredi")
                        .HasColumnType("real");

                    b.Property<DateTime>("YaratilmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("DersKodu");

                    b.HasIndex("BolumID");

                    b.HasIndex("EOYiliID");

                    b.ToTable("DerslerTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EOYiliTbl", b =>
                {
                    b.Property<int>("EOYiliID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EOYiliID"));

                    b.Property<string>("EOYili")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EOYiliID");

                    b.ToTable("EOYiliTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.GorevlerTbl", b =>
                {
                    b.Property<int>("GorevID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevID"));

                    b.Property<string>("GorevAdi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("GorevID");

                    b.ToTable("GorevlerTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.KisimDegerlendirmeleriTbl", b =>
                {
                    b.Property<int>("KisimDegerlendirmeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KisimDegerlendirmeID"));

                    b.Property<int>("EOYiliID")
                        .HasColumnType("int");

                    b.Property<string>("KisimAdi")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("KisimDegerlendirme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("datetime2");

                    b.HasKey("KisimDegerlendirmeID");

                    b.ToTable("KisimDegerlendirmeleriTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.KisimlarTbl", b =>
                {
                    b.Property<string>("KisimAdi")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("BolumID")
                        .HasColumnType("int");

                    b.Property<int?>("Sinif")
                        .HasColumnType("int");

                    b.HasKey("KisimAdi");

                    b.HasIndex("BolumID");

                    b.ToTable("KisimlarTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrenciBilgileriTbl", b =>
                {
                    b.Property<long>("OgrBilgiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OgrBilgiID"));

                    b.Property<string>("AnneAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AnneBabaMedeniDurum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AnneEgitim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AnneGelir")
                        .HasColumnType("int");

                    b.Property<string>("BabaAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BabaEgitim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BabaGelir")
                        .HasColumnType("int");

                    b.Property<float>("DisiplinPuani")
                        .HasColumnType("real");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DogumYeri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KardesSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<float>("LiseDiplomaNotu")
                        .HasColumnType("real");

                    b.Property<float>("MSUPuani")
                        .HasColumnType("real");

                    b.Property<float>("OSYMPuani")
                        .HasColumnType("real");

                    b.Property<int>("OgrenciGelir")
                        .HasColumnType("int");

                    b.Property<long>("OgrenciID")
                        .HasColumnType("bigint");

                    b.Property<string>("OgrenciTC")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("OkulaGirisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("OgrBilgiID");

                    b.HasIndex("OgrenciID")
                        .IsUnique();

                    b.ToTable("OgrenciBilgileriTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrenciDegerlendirmeTurleriTbl", b =>
                {
                    b.Property<int>("DegTurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegTurID"));

                    b.Property<string>("TurAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DegTurID");

                    b.ToTable("OgrenciDegerlendirmeTurleriTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrenciDegerlendirmeleriTbl", b =>
                {
                    b.Property<int>("DegerlendirmeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegerlendirmeID"));

                    b.Property<int>("DegTurID")
                        .HasColumnType("int");

                    b.Property<string>("Degerlendirme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Donem")
                        .HasColumnType("int");

                    b.Property<int>("EOYiliID")
                        .HasColumnType("int");

                    b.Property<long>("OgrenciID")
                        .HasColumnType("bigint");

                    b.Property<int>("PerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("datetime2");

                    b.HasKey("DegerlendirmeID");

                    b.HasIndex("DegTurID");

                    b.HasIndex("EOYiliID");

                    b.HasIndex("OgrenciID")
                        .IsUnique();

                    b.HasIndex("PerID")
                        .IsUnique();

                    b.ToTable("OgrenciDegerlendirmeleriTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrencilerTbl", b =>
                {
                    b.Property<long>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OgrenciID"));

                    b.Property<string>("Adi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AskeriSinifID")
                        .HasColumnType("int");

                    b.Property<bool>("Ayrildi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AyrilmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Boluk")
                        .HasColumnType("int");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyeti")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EPosta")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FotografAdresi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("KisimAdi")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("Mezun")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MezuniyetTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgrenciTC")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tabur")
                        .HasColumnType("int");

                    b.Property<int>("UyrukID")
                        .HasColumnType("int");

                    b.Property<int>("YakaNo")
                        .HasColumnType("int");

                    b.HasKey("OgrenciID");

                    b.HasIndex("BolumID");

                    b.HasIndex("KisimAdi");

                    b.HasIndex("UyrukID");

                    b.ToTable("OgrencilerTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.PersonelTbl", b =>
                {
                    b.Property<int>("PerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerId"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("BirimID")
                        .HasColumnType("int");

                    b.Property<int?>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("CepTelefonu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DahiliTelefonu")
                        .HasColumnType("int");

                    b.Property<string>("DigerEPosta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GorevID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MisafirEvAdresi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MisafirGorevYeri")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("MisafirPersonel")
                        .HasColumnType("bit");

                    b.Property<string>("OkulEPosta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonelTC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("RutbeID")
                        .HasColumnType("int");

                    b.Property<int?>("SinifID")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UnvanID")
                        .HasColumnType("int");

                    b.HasKey("PerId");

                    b.HasIndex("BirimID");

                    b.HasIndex("BolumID");

                    b.HasIndex("GorevID");

                    b.HasIndex("RutbeID");

                    b.HasIndex("SinifID");

                    b.HasIndex("UnvanID");

                    b.ToTable("PersonelTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.RutbeTbl", b =>
                {
                    b.Property<int>("RutbeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutbeID"));

                    b.Property<string>("RutbeKisa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RutbeUzun")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RutbeID");

                    b.ToTable("RutbeTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UnvanTbl", b =>
                {
                    b.Property<int>("UnvanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnvanID"));

                    b.Property<string>("UnvanKisa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UnvanUzun")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UnvanID");

                    b.ToTable("UnvanTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UyrukTbl", b =>
                {
                    b.Property<int>("UyrukID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UyrukID"));

                    b.Property<string>("Uyruk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UyrukID");

                    b.ToTable("UyrukTbl");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.DerslerTbl", b =>
                {
                    b.HasOne("EntityLayer.Concrete.BolumTbl", "BolumTbl")
                        .WithMany("DerslerTbl")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.EOYiliTbl", "EOYiliTbl")
                        .WithMany("DerslerTbl")
                        .HasForeignKey("EOYiliID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BolumTbl");

                    b.Navigation("EOYiliTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.KisimlarTbl", b =>
                {
                    b.HasOne("EntityLayer.Concrete.BolumTbl", "BolumTbl")
                        .WithMany("KisimlarTbl")
                        .HasForeignKey("BolumID");

                    b.Navigation("BolumTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrenciBilgileriTbl", b =>
                {
                    b.HasOne("EntityLayer.Concrete.OgrencilerTbl", "OgrencilerTbl")
                        .WithOne("OgrenciBilgileriTbl")
                        .HasForeignKey("EntityLayer.Concrete.OgrenciBilgileriTbl", "OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OgrencilerTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrenciDegerlendirmeleriTbl", b =>
                {
                    b.HasOne("EntityLayer.Concrete.OgrenciDegerlendirmeTurleriTbl", "OgrenciDegerlendirmeTurleriTbl")
                        .WithMany("OgrenciDegerlendirmeleriTbl")
                        .HasForeignKey("DegTurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.EOYiliTbl", "EOYiliTbl")
                        .WithMany()
                        .HasForeignKey("EOYiliID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.OgrencilerTbl", "OgrencilerTbl")
                        .WithOne("OgrenciDegerlendirmeleriTbl")
                        .HasForeignKey("EntityLayer.Concrete.OgrenciDegerlendirmeleriTbl", "OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.PersonelTbl", "PersonelTbl")
                        .WithOne("OgrenciDegerlendirmeleriTbl")
                        .HasForeignKey("EntityLayer.Concrete.OgrenciDegerlendirmeleriTbl", "PerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EOYiliTbl");

                    b.Navigation("OgrenciDegerlendirmeTurleriTbl");

                    b.Navigation("OgrencilerTbl");

                    b.Navigation("PersonelTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrencilerTbl", b =>
                {
                    b.HasOne("EntityLayer.Concrete.BolumTbl", "BolumTbl")
                        .WithMany("OgrencilerTbl")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.KisimlarTbl", "KisimlarTbl")
                        .WithMany("OgrencilerTbl")
                        .HasForeignKey("KisimAdi");

                    b.HasOne("EntityLayer.Concrete.UyrukTbl", "UyrukTbl")
                        .WithMany("OgrencilerTbl")
                        .HasForeignKey("UyrukID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BolumTbl");

                    b.Navigation("KisimlarTbl");

                    b.Navigation("UyrukTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.PersonelTbl", b =>
                {
                    b.HasOne("EntityLayer.Concrete.BirimlerTbl", "BirimlerTbl")
                        .WithMany("PersonelTbl")
                        .HasForeignKey("BirimID");

                    b.HasOne("EntityLayer.Concrete.BolumTbl", "BolumTbl")
                        .WithMany("PersonelTbl")
                        .HasForeignKey("BolumID");

                    b.HasOne("EntityLayer.Concrete.GorevlerTbl", "GorevlerTbl")
                        .WithMany("PersonelTbl")
                        .HasForeignKey("GorevID");

                    b.HasOne("EntityLayer.Concrete.RutbeTbl", "RutbeTbl")
                        .WithMany("PersonelTbl")
                        .HasForeignKey("RutbeID");

                    b.HasOne("EntityLayer.Concrete.AskeriSiniflarTbl", "AskeriSiniflarTbl")
                        .WithMany("PersonelTbl")
                        .HasForeignKey("SinifID");

                    b.HasOne("EntityLayer.Concrete.UnvanTbl", "UnvanTbl")
                        .WithMany("PersonelTbl")
                        .HasForeignKey("UnvanID");

                    b.Navigation("AskeriSiniflarTbl");

                    b.Navigation("BirimlerTbl");

                    b.Navigation("BolumTbl");

                    b.Navigation("GorevlerTbl");

                    b.Navigation("RutbeTbl");

                    b.Navigation("UnvanTbl");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppRolesTbl", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUserTbl", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUserTbl", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppRolesTbl", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.AppUserTbl", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AppUserTbl", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Concrete.AskeriSiniflarTbl", b =>
                {
                    b.Navigation("PersonelTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.BirimlerTbl", b =>
                {
                    b.Navigation("PersonelTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.BolumTbl", b =>
                {
                    b.Navigation("DerslerTbl");

                    b.Navigation("KisimlarTbl");

                    b.Navigation("OgrencilerTbl");

                    b.Navigation("PersonelTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EOYiliTbl", b =>
                {
                    b.Navigation("DerslerTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.GorevlerTbl", b =>
                {
                    b.Navigation("PersonelTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.KisimlarTbl", b =>
                {
                    b.Navigation("OgrencilerTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrenciDegerlendirmeTurleriTbl", b =>
                {
                    b.Navigation("OgrenciDegerlendirmeleriTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrencilerTbl", b =>
                {
                    b.Navigation("OgrenciBilgileriTbl")
                        .IsRequired();

                    b.Navigation("OgrenciDegerlendirmeleriTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.PersonelTbl", b =>
                {
                    b.Navigation("OgrenciDegerlendirmeleriTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.RutbeTbl", b =>
                {
                    b.Navigation("PersonelTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UnvanTbl", b =>
                {
                    b.Navigation("PersonelTbl");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UyrukTbl", b =>
                {
                    b.Navigation("OgrencilerTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
