// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.AskeriSiniflarTbl", b =>
                {
                    b.Property<int>("SinifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinifID"));

                    b.Property<string>("SinifKisa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SinifUzun")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SinifID");

                    b.ToTable("AskeriSiniflars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.BirimlerTbl", b =>
                {
                    b.Property<int>("BirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BirimID"));

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BirimID");

                    b.ToTable("Birimlers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.BolumTbl", b =>
                {
                    b.Property<int>("BolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumID"));

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BolumID");

                    b.ToTable("Bolums");
                });

            modelBuilder.Entity("EntityLayer.Concrete.DerslerTbl", b =>
                {
                    b.Property<string>("DersKodu")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("AKTS")
                        .HasColumnType("int");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EOYiliID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HaftalikDS")
                        .HasColumnType("int");

                    b.Property<decimal>("Kredi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("YaratilmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("DersKodu");

                    b.ToTable("Derslers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EOYiliTbl", b =>
                {
                    b.Property<int>("EOYiliID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EOYiliID"));

                    b.Property<string>("EOYili")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EOYiliID");

                    b.ToTable("EOYilis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.GorevlerTbl", b =>
                {
                    b.Property<int>("GorevID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevID"));

                    b.Property<string>("GorevAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("GorevID");

                    b.ToTable("Gorevlers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.KisimlarTbl", b =>
                {
                    b.Property<long>("KisimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KisimID"));

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("KisimAdi")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.HasKey("KisimID");

                    b.ToTable("Kisimlars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrenciBilgileriTbl", b =>
                {
                    b.Property<long>("OgrenciTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OgrenciTC"));

                    b.Property<string>("AnneAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AnneBabaMedeniDurum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AnneEgitim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AnneGelir")
                        .HasColumnType("int");

                    b.Property<string>("BabaAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BabaEgitim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BabaGelir")
                        .HasColumnType("int");

                    b.Property<float>("DisiplinPuani")
                        .HasColumnType("real");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DogumYeri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KardesSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<float>("LiseDiplomaNotu")
                        .HasColumnType("real");

                    b.Property<float>("MSUPuani")
                        .HasColumnType("real");

                    b.Property<float>("OSYMPuani")
                        .HasColumnType("real");

                    b.Property<int>("OgrenciGelir")
                        .HasColumnType("int");

                    b.Property<DateTime>("OkulaGirisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("OgrenciTC");

                    b.ToTable("OgrenciBilgileris");
                });

            modelBuilder.Entity("EntityLayer.Concrete.OgrencilerTbl", b =>
                {
                    b.Property<long>("OgrenciTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OgrenciTC"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AskeriSinifID")
                        .HasColumnType("int");

                    b.Property<bool>("Ayrildi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AyrilmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Boluk")
                        .HasColumnType("int");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyeti")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FotografAdresi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("KisimAdi")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("Mezun")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MezuniyetTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tabur")
                        .HasColumnType("int");

                    b.Property<int>("UyrukID")
                        .HasColumnType("int");

                    b.Property<int>("YakaNo")
                        .HasColumnType("int");

                    b.HasKey("OgrenciTC");

                    b.ToTable("Ogrencilers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.PersonelTbl", b =>
                {
                    b.Property<long>("PersonelTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersonelTC"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BirimID")
                        .HasColumnType("int");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("CepTelefonu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DahiliTelefonu")
                        .HasColumnType("int");

                    b.Property<string>("DigerEPosta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GorevID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MisafirEvAdresi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MisafirGorevYeri")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("MisafirPersonel")
                        .HasColumnType("bit");

                    b.Property<string>("OkulEPosta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RutbeID")
                        .HasColumnType("int");

                    b.Property<int>("SinifID")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UnvanID")
                        .HasColumnType("int");

                    b.HasKey("PersonelTC");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ProfilTbl", b =>
                {
                    b.Property<int>("ProfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfilID"));

                    b.Property<string>("ProfilAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProfilID");

                    b.ToTable("Profils");
                });

            modelBuilder.Entity("EntityLayer.Concrete.RutbeTbl", b =>
                {
                    b.Property<int>("RutbeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutbeID"));

                    b.Property<string>("RutbeKisa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RutbeUzun")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RutbeID");

                    b.ToTable("Rutbes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UnvanTbl", b =>
                {
                    b.Property<int>("UnvanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnvanID"));

                    b.Property<string>("UnvanKisa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UnvanUzun")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UnvanID");

                    b.ToTable("Unvans");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Users", b =>
                {
                    b.Property<long>("UserTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserTC"));

                    b.Property<bool>("Pasif")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProfilID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SifreGuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("YaratilmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("UserTC");

                    b.ToTable("users");
                });

            modelBuilder.Entity("EntityLayer.Concrete.UyrukTbl", b =>
                {
                    b.Property<int>("UyrukID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UyrukID"));

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UyrukID");

                    b.ToTable("Uyruks");
                });
#pragma warning restore 612, 618
        }
    }
}
